export const projects = [
    {
        id: 1,
        title: 'Projeto-fetch-github-api',
        description: 'Este projeto é uma aplicação web que permite buscar usuários do GitHub e exibir suas informações, como nome, bio e repositórios públicos.',
        image: './src/assets/images/projeto-fetch-github.png',
        repoLink: 'https://github.com/cassio-leite/projeto-fetch-github-api.git',
        liveLink: 'https://cassio-leite.github.io/projeto-fetch-github-api/',
    },
    {
        id: 2,
        title: 'Gerador de Conselhos',
        description: 'Um projeto simples e interativo que gera conselhos aleatórios consumindo a API pública Advice Slip API.',
        image: './src/assets/images/projeto-gerador-de-conselhos.png',
        repoLink: 'https://github.com/cassio-leite/Gerador-de-conselhos.git',
        liveLink: 'https://cassio-leite.github.io/Gerador-de-conselhos/',
    },
    {
        id: 3,
        title: 'Previsão do Tempo',
        description: 'Projeto simples e funcional de uma aplicação web que exibe a previsão do tempo atual para qualquer cidade informada.',
        image: './src/assets/images/projeto-clima.png',
        repoLink: 'https://github.com/cassio-leite/Projeto-clima.git',
        liveLink: 'https://cassio-leite.github.io/Projeto-clima/',
    },
    {
        id: 4,
        title: 'Formulário com Validação',
        description: 'Este projeto é um formulário de contato com validação de campos obrigatórios.',
        image: './src/assets/images/projeto-formulario.png',
        repoLink: 'https://github.com/cassio-leite/f-o-r-m-u-l-a-r-i-o.git',
        liveLink: 'https://cassio-leite.github.io/f-o-r-m-u-l-a-r-i-o/',
    },
    {
        id: 5,
        title: 'Lista de Livros para Programadores',
        description: 'Este projeto é um site interativo que apresenta uma lista de livros essenciais para programadores.',
        image: './src/assets/images/projeto-livros-para-programadores.png',
        repoLink: 'https://github.com/cassio-leite/livros-para-desenvolvedores.git',
        liveLink: 'https://cassio-leite.github.io/livros-para-desenvolvedores/',
    },
    {
        id: 6,
        title: 'projeto-e-commerce-perfume',
        description: 'Este projeto é uma loja virtual de perfumes, onde os usuários podem navegar e comprar fragrâncias.',
        image: './src/assets/images/projeto-e-commerce-perfume.png',
        repoLink: 'https://github.com/cassio-leite/projeto-e-commerce-perfume.git',
        liveLink: 'https://cassio-leite.github.io/projeto-e-commerce-perfume/',
    },
];